# Generated by Django 1.9.12 on 2017-02-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formidable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='display',
        ),
    ]
