# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-26 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formidable', '0003_item_label_no_size_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='formidable',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
