# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-23 10:37
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formidable', '0008_formidable_item_value_field_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='parameters',
            field=jsonfield.fields.JSONField(
                blank=True, default={}, null=True
            ),
        ),
    ]
