# Generated by Django 2.2.19 on 2021-03-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formidable', '0010_auto_20200213_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formidable',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
