runserver:
	python manage.py runserver

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  runserver to run the development server"
	@echo "  populate  to setup the database with fixtures"

populate:
	python manage.py populate fixtures/*.json
